version: "3"

services:
  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    ports:
      - 80:80
    volumes:
      - ./:/var/www
      - .docker/nginx/app.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - breaking-bad

  app:
    container_name: app
    build:
      context: .docker/app
      dockerfile: Dockerfile
    working_dir: '/var/www'
    env_file:
        - .docker/app/.env
    volumes:
      - './:/var/www'
      - '.docker/app/supervisor/supervisord.conf:/etc/supervisord.conf'
      - '.docker/app/supervisor/horizon.conf:/etc/supervisor/conf.d/horizon.conf'
    user: docker
    command: [ "/usr/bin/supervisord", "-n", "-c", "/etc/supervisord.conf"]
    ports:
      - 3000:80
    depends_on:
      - mysql
      - redis
    networks:
      - breaking-bad

  pma:
    container_name: pma
    image: phpmyadmin:latest
    restart: always
    ports:
      - 8080:80
    environment:
      PMA_HOST: mysql
      UPLOAD_LIMIT: 300M
    depends_on:
      - mysql
    networks:
      - breaking-bad

  mysql:
    container_name: mysql
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: breakingbad
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - .docker/mysql:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      - breaking-bad

  redis:
    container_name: redis
    image: redis:alpine
    hostname: redis
    restart: always
    command: "redis-server --appendonly yes --replica-read-only no"
    ports:
      - 6379:6379
    networks:
      - breaking-bad

networks:
  breaking-bad:
    driver: bridge
